# -*- coding: utf-8 -*-
"""MiroFish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1INw5016joY6hcq7rk5x5A82s_n6aZrOw

Requires python < 12 (In colab it is 2025.07) with a100 high ram (80gb)
"""

# Install Colab-only dependencies (pyngrok for tunneling)
!pip install pyngrok

# Install uv (fast Python package manager — same tool used in Dockerfile)
!pip install uv

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !sudo apt update && sudo apt install -y pciutils zstd
# !curl -fsSL https://ollama.com/install.sh | sh

import os
import subprocess
import time
from google.colab import userdata
from pyngrok import ngrok

env = os.environ.copy()
env["OLLAMA_NUM_PARALLEL"] = "5"       # Allow 5 simultaneous agent requests
env["OLLAMA_MAX_QUEUE"] = "64"         # Don't drop requests, queue them up
env["OLLAMA_FLASH_ATTENTION"] = "1"    # Speed up large context windows (Flash Attention)
env['CUDA_VISIBLE_DEVICES'] = '0'      # Force it to use the GPU
env["OLLAMA_KV_CACHE_TYPE"] = "q8_0"   # Quantize KV cache to save even more VRAM

# Create the logs directory if it doesn't exist
log_dir = '/content/logs'
os.makedirs(log_dir, exist_ok=True)

ollama_proc = subprocess.Popen(
    ['ollama', 'serve'],
    stdout=open(os.path.join(log_dir, 'ollama.log'), 'w'),
    stderr=subprocess.STDOUT,
    env=env
)
time.sleep(5)
!echo "✅ Ollama server started (PID: $(pgrep ollama))"

!ollama pull qwen2.5:14b
!ollama pull nomic-embed-text
!ollama list
!echo "✅ All models ready"

def setup_git_repo(repo_url, base_path="/content"):
    """
    Clones a git repository or pulls updates if it already exists.

    Args:
        repo_url (str): The HTTPS URL of the GitHub repository.
        base_path (str): The local directory where the repo should live.
    """
    # Ensure we are in the correct base directory
    os.chdir(base_path)

    # Extract the repository name from the URL (e.g., 'raise-26')
    repo_dir = repo_url.split("/")[-1].replace(".git", "")
    repo_path = os.path.join(base_path, repo_dir)

    if os.path.exists(repo_path):
        print(f"Directory '{repo_dir}' exists. Pulling latest changes...")
        # Run git pull inside the specific directory
        subprocess.run(["git", "-C", repo_path, "pull"], check=True)
    else:
        print(f"Directory '{repo_dir}' not found. Cloning...")
        subprocess.run(["git", "clone", repo_url], check=True)

    return repo_path

# Clone MiroFish-Offline & Write .env
setup_git_repo("https://github.com/pandevim/MiroFish-Offline.git")

# Sync backend dependencies from lockfile (reproducible — same as Docker)
!cd /content/MiroFish-Offline/backend && uv sync --frozen

# === RESTORE checkpoint from Google Drive ===
from google.colab import drive
drive.mount('/content/drive')

import shutil
save_dir = '/content/drive/MyDrive/MiroFish_checkpoint'

if os.path.exists(f'{save_dir}/uploads'):
    shutil.copytree(
        f'{save_dir}/uploads',
        '/content/MiroFish-Offline/backend/uploads',
        dirs_exist_ok=True
    )
    print("✅ Checkpoint restored — skip to /api/simulation/start")
else:
    print("❌ No checkpoint found, run full pipeline")

MY_NEO4J_URI = "neo4j+s://10b738ee.databases.neo4j.io" # connection_info['bolt_url']
MY_NEO4J_USER = "10b738ee" # connection_info['username']
MY_NEO4J_PASSWORD = "lsypUWYzFNuhbcfhcBYpMlpuoWl4NX7sTDRJQKcFcgk" # connection_info['password']
MY_LLM_MODEL = "qwen2.5:14b"

# Write .env with AuraDB credentials, Ollama config, and OASIS config
env_content = f"""# === LLM (Ollama on Colab GPU) ===
LLM_API_KEY=ollama
LLM_BASE_URL=http://localhost:11434/v1
LLM_MODEL_NAME={MY_LLM_MODEL}

# === Neo4j AuraDB ===
NEO4J_URI={MY_NEO4J_URI}
NEO4J_USER={MY_NEO4J_USER}
NEO4J_PASSWORD={MY_NEO4J_PASSWORD}

# === Embeddings (Ollama) ===
EMBEDDING_MODEL=nomic-embed-text
EMBEDDING_BASE_URL=http://localhost:11434

# === OASIS / CAMEL-AI Configuration ===
OPENAI_API_KEY=ollama
OPENAI_API_BASE_URL=http://localhost:11434/v1
OPENAI_BASE_URL=http://localhost:11434/v1
"""

# Remember to save it inside the cloned repo!
with open('/content/MiroFish-Offline/.env', 'w') as f:
    f.write(env_content)

print('✅ .env written successfully!')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !cd /content/MiroFish-Offline/frontend && npm install && npm run build

# Start backend in background
backend_proc = subprocess.Popen(
    ['uv', 'run', 'python', 'run.py'],
    stdout=open(os.path.join(log_dir, 'mirofish_backend.log'), 'w'),
    stderr=subprocess.STDOUT,
    cwd='/content/MiroFish-Offline/backend'
)
time.sleep(5)
print(f'✅ Backend running (PID: {backend_proc.pid})')

token = userdata.get('NGROK_AUTH_TOKEN')
!ngrok config add-authtoken {token}
print("🚀 MiroFish App URL:", ngrok.connect(5001))

# !pkill -f "ollama"
# backend_proc.kill()
# !fuser -k 5001/tcp
# !rm -rf /content/MiroFish-Offline/
!tail -n 50 /content/logs/mirofish_backend.log
# !tail -n 100 /content/logs/ollama.log

# === SAVE checkpoint to Google Drive ===
from google.colab import drive
drive.mount('/content/drive')

import shutil
save_dir = '/content/drive/MyDrive/MiroFish_checkpoint'
os.makedirs(save_dir, exist_ok=True)

# Save both uploads directories
shutil.copytree(
    '/content/MiroFish-Offline/backend/uploads',
    f'{save_dir}/uploads',
    dirs_exist_ok=True
)
print("✅ Checkpoint saved to Google Drive")